server:
  port: 8080
  
spring:
  application:
    name: simple-order
 
eureka:
  client:
    register-with-eureka: true #是否将自己注册到服务中
    fetch-registry: true #是否从eureka中返回注册信息
    service-url:
      defaultZone:  http://username:password@127.0.0.1:8086/eureka/ #defaultZone不能用-连接只能用驼峰，如果有多个用逗号隔开
  instance:
    prefer-ip-address: true #将本机ip注册到中心
    ip-address: 127.0.0.1 #别人调用时使用的ip
    instance-id: simple-order #实例名
simple-item:
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule #设置simple-item服务的负载均衡策略为随机,默认为轮询